import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const file = path => readFileSync(new URL("../"+path,import.meta.url),"utf8");
const index = file("index.html"), lab = file("laboratorio.html"), privacy=file("privacidad.html");
const site = file("assets/js/site.js"), theme=file("assets/js/theme.js");
const thanks = file("gracias.html"), thanksJs = file("assets/js/thanks.js");
const app = file("assets/js/app.js"), css=file("assets/css/main.css");
const commercialCss=file("assets/css/commercial.css");

test("commercial story: client problem, solutions, scope, proof, process and contact precede the lab",()=>{
 const names=["problemas","servicios","oferta","casos","proceso","contacto","playground"];
 const positions=names.map(id=>index.indexOf('id="'+id+'"'));
 assert.ok(positions.every(n=>n>0));
 for(let i=1;i<positions.length;i++)assert.ok(positions[i]>positions[i-1],names[i]+" out of order");
 assert.match(index,/Cuéntame qué necesitas ↗/);
 assert.match(index,/Necesita mejores sistemas/);
});

test("offer: three grounded service pillars and six filterable examples",()=>{
 assert.equal((index.match(/class="service-pillar reveal"/g)||[]).length,3);
 assert.equal((index.match(/class="service-card reveal"/g)||[]).length,6);
 for(const key of ["all","automation","data","apps","ai"])
  assert.match(index,new RegExp('data-filter="'+key+'"'));
 assert.match(site,/initFilters/);
});

test("V44 service filters truly hide nonmatching cards and report result counts",()=>{
 assert.match(css,/\.service-card\[hidden\]\{display:none!important\}/);
 assert.match(index,/id="filterStatus"[^>]*role="status"/);
 assert.match(index,/id="serviceResults"/);
 assert.equal((index.match(/aria-controls="serviceResults"/g)||[]).length,5);
 assert.match(site,/if \(!card\.hidden\) visible\+\+/);
 assert.match(site,/status\.textContent = "Mostrando "/);
 assert.match(css,/\.filter-btn\{min-height:44px\}/);
});

test("V44 mobile menu closes accessibly and compact cases have intentional grid hierarchy",()=>{
 assert.match(site,/button\.focus\(\)/);
 assert.match(site,/event\.key !== "Escape"/);
 assert.match(site,/menu\.contains\(event\.target\)/);
 assert.match(site,/\(min-width: 961px\)/);
 assert.match(css,/\.mobile-nav\.is-open\{max-height:calc\(100dvh - 82px\)/);
 assert.match(css,/\.case-studies \.study-card:first-child\{grid-column:1\/-1\}/);
 assert.match(css,/\.notice-inner\{overflow:visible;white-space:normal/);
});

test("V45 commercial stylesheet excludes the V40-only block without visual cascade changes",()=>{
 const start = "/* Technical playground */";
 const end = "/* Commercial-first presentation, without changing the V40 decision engine. */";
 const a=css.indexOf(start), b=css.indexOf(end);
 assert.ok(a>0 && b>a,"lab CSS cut boundaries");
 const expected="/* AUTOGENERATED from main.css; run node scripts/build-commercial-css.mjs */\\n"+
   css.slice(0,a)+css.slice(b);
 assert.equal(commercialCss,expected,"regenerate commercial.css after editing main.css");
 assert.ok(Buffer.byteLength(commercialCss,"utf8")<=55000,"commercial CSS must stay within 55 KB uncompressed");
 assert.ok(Buffer.byteLength(commercialCss)<Buffer.byteLength(css)*0.60,"landing stylesheet budget");
 assert.ok(Buffer.byteLength(site,"utf8")<=18500,"site.js must stay within 18.5 KB");
 for(const page of [index,privacy,thanks]){
   assert.match(page,/assets\\/css\\/commercial\\.css/);
   assert.doesNotMatch(page,/assets\\/css\\/main\\.css/);
 }
 assert.match(lab,/assets\\/css\\/main\\.css/);
 assert.doesNotMatch(lab,/assets\\/css\\/commercial\\.css/);
 assert.match(index,/script async fetchpriority="low" data-domain="gracianb\\.github\\.io\\/revops-studio"/);
});

test("commercial pricing stays indicative, without invented savings",()=>{
 for(const price of ["900 €","4.000 €","600 €"])assert.ok(index.includes(price));
 assert.match(index,/No se promete un porcentaje de ahorro/);
 assert.match(site,/Coste del tiempo, no ahorro prometido/);
});

test("calculator-to-contact handoff is optional, removable and not a savings claim",()=>{
 assert.match(index,/id="calcToContact"[^>]+href="#contacto"/);
 assert.match(index,/id="estimacion"[^>]*value=""/);
 assert.match(index,/id="calcContextClear"/);
 assert.match(site,/calculatorScenario/);
 assert.match(site,/form\.dispatchEvent\(new Event\("input"/);
 assert.match(site,/estimateField\.value = ""/);
 assert.match(site,/\.\.\.\(brief\.estimacion \? \{ estimacion: brief\.estimacion \} : \{\}\)/);
 assert.match(site,/Coste teórico del tiempo, no ahorro prometido/);
});

test("confirmation requires accepted provider response in the current tab",()=>{
 assert.match(site,/sessionStorage\.setItem\(ACCEPTED_KEY, "true"\)/);
 assert.match(site,/sessionStorage\.removeItem\(ACCEPTED_KEY\)/);
 assert.match(thanksJs,/&& confirmedInSession/);
 assert.match(thanksJs,/no confirma un envío sin una aceptación previa/);
});

test("public and private professional cases remain clearly distinguished",()=>{
 for(const slug of ["proyecto-bodytone.html","proyecto-calculadora.html","proyecto-outreach.html"])
  assert.ok(index.includes(slug));
 assert.match(index,/bodytonehelp.zendesk.com/);
 assert.match(index,/Lógica privada/);
 assert.match(index,/Sistema privado/);
 assert.equal((index.match(/class="study-card reveal"/g)||[]).length,3);
 assert.equal((index.match(/class="case-visual /g)||[]).length,3);
});

test("V43 case evidence is specific, public/private boundaries stay honest",()=>{
 const cards=[...index.matchAll(/<article class="study-card reveal" data-case-id="([^"]+)">/g)].map(m=>m[1]);
 assert.deepEqual(cards,["bodytone","calculadora","outreach"]);
 assert.equal((index.match(/class="study-proof"/g)||[]).length,3);
 assert.equal((index.match(/class="study-decisions"/g)||[]).length,3);
 assert.equal((index.match(/class="study-discuss"/g)||[]).length,3);
 for(const id of cards) assert.match(index,new RegExp('data-case-choice="'+id+'"'));
 assert.match(index,/Centro de ayuda real, público y navegable/);
 assert.match(index,/Tarifas, fórmulas y datos de clientes permanecen privados/);
 assert.match(index,/No se publican bases reales, contactos, credenciales ni tasas de conversión/);
 assert.match(index,/id="caseContextClear"/);
 assert.match(css,/study-decisions summary:focus-visible/);
});

test("V43 case choice is removable, never overwrites visitor prose or sends without consent",()=>{
 assert.match(site,/const CASE_REFERENCES = Object\.freeze/);
 assert.match(site,/if \(!select\.value\) select\.value = selected\.service/);
 assert.match(site,/function initCaseChoice/);
 assert.match(site,/function showCaseContext/);
 assert.match(site,/\[data-case-choice\]/);
 assert.match(site,/caseContextClear/);
 assert.match(site,/caso_referencia: String\(data\.caso_referencia/);
 assert.match(site,/\.\.\.\(brief\.caso_referencia \? \{ caso_referencia: brief\.caso_referencia \} : \{\}\)/);
 assert.match(site,/Caso de referencia: /);
 assert.match(thanksJs,/Caso de referencia: /);
 assert.match(site,/initBriefForm\(\);\s*initCaseChoice\(\);/);
});

test("contact: real provider endpoint, required consent, explained processing and email fallback",()=>{
 assert.match(index,/id="briefForm"[^>]+method="POST"/);
 assert.match(index,/action="https:\/\/formsubmit\.co\/gracianbaenagonzalez@gmail\.com"/);
 assert.match(index,/id="privacyConsent"[^>]*required/);
 assert.match(index,/assets\/js\/theme\.js/);
 assert.match(index,/id="briefEmailFallback"/);
 assert.match(index,/privacidad\.html/);
 assert.match(site,/https:\/\/formsubmit\.co\/ajax\/gracianbaenagonzalez@gmail\.com/);
 assert.match(site,/AbortController/);
 assert.match(site,/form\.checkValidity/);
 assert.match(site,/updateFallback/);
 assert.match(site,/response\.ok/);
 assert.match(site,/Provider rejected submission/);
 assert.doesNotMatch(site,/Enviar solicitud recibida/i);
});

test("contact confirmation never misrepresents provider acceptance as mailbox delivery",()=>{
 assert.match(thanksJs,/no la entrega al buzón ni la lectura del mensaje/);
 assert.doesNotMatch(thanksJs,/recepción requiere la activación inicial/);
 assert.match(thanks,/La solicitud todavía no se ha enviado/);
 assert.match(thanks,/id="sendBrief"/);
 assert.match(thanks,/assets\/js\/theme\.js/);
});

test("privacy page discloses actual form processing, data rights and owner contact",()=>{
 assert.match(privacy,/FormSubmit/);
 assert.match(privacy,/supresión/);
 assert.match(privacy,/gracianbaenagonzalez@gmail\.com/);
 assert.match(privacy,/AEPD/);
});

test("dark / light mode script is available on landing, laboratory and confirmation",()=>{
 for(const page of [index,lab,thanks,privacy])assert.match(page,/assets\/js\/theme\.js/);
 assert.match(theme,/revops-theme/);
 assert.match(theme,/localStorage\.setItem/);
 assert.match(theme,/aria-pressed/);
 assert.match(css,/:root\[data-theme="light"\]/);
 assert.match(css,/:root\[data-theme="dark"\]/);
});

test("V40 laboratory remains separate and runnable with synthetic data",()=>{
 assert.match(index,/href="\.\/laboratorio\.html"/);
 assert.match(index,/src="\.\/assets\/js\/site\.js"/);
 assert.doesNotMatch(index,/src="\.\/assets\/js\/app\.js"/);
 assert.match(lab,/src="\.\/assets\/js\/app\.js"/);
 assert.match(lab,/id="demoRows"/);
 assert.match(app,/initPlayground\(\)/);
 assert.deepEqual([...lab.matchAll(/data-guided-step="(\d+)"/g)].map(m=>Number(m[1])),[0,1,2,3]);
});

test("legacy shared configurations still open the isolated lab",()=>{
 assert.match(site,/window\.location\.hash\.startsWith\("#config="\)/);
 assert.match(site,/window\.location\.replace\("\.\/laboratorio\.html" \+ window\.location\.hash\)/);
});

test("all pages have unique IDs and working same-page hash links",()=>{
 for(const [name,page] of [["index",index],["laboratorio",lab],["gracias",thanks],["privacidad",privacy]]) {
  const ids=[...page.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
  assert.equal(ids.length,new Set(ids).size,name+" duplicate ID");
  for(const href of page.matchAll(/href="#([^"]+)"/g))assert.ok(ids.includes(href[1]),name+" broken #"+href[1]);
 }
});

test("FormSubmit activation: explain rejected delivery without claiming success",()=>{
 assert.match(site,/providerSaidActivation/);
 assert.match(site,/propietario active el formulario/);
 assert.match(site,/Puede faltar la activación inicial del formulario/);
 assert.match(site,/error\?\.name === "AbortError"/);
 assert.match(site,/No hay entrega confirmada/);
 assert.match(site,/if \(fallback\) fallback\.focus\(\)/);
});
